baseURL = "https://worfinka.github.io/tastyink/"
defaultContentLanguage = "ru"
title = "TastyInk"

[permalinks]
stories = "/:language/stories/:slug/"

[languages]
  [languages.ru]
    title = "TastyInk"
    weight = 1
    label = "Русский"
  [languages.en]
    title = "TastyInk"
    weight = 2
    label = "English"

[imaging]
resampleFilter = "box"
quality = 85
anchor = "smart"

[sitemap]
changefreq = "weekly"
priority = 0.5

[outputs]
home = ["HTML", "RSS", "JSON"]
