baseURL = "https://worfinka.github.io/tastyink/"
defaultContentLanguage = "ru"
title = "TastyInk"

# Включаем красивые URL (без .html)
[permalinks]
  stories = "/:language/stories/:slug/"

# Мультиязычность
[languages]
  [languages.ru]
    title = "TastyInk"
    weight = 1
    label = "Русский"
  [languages.en]
    title = "TastyInk"
    weight = 2
    label = "English"

# Настройки для картинок (чтобы Hugo обрабатывал их)
[imaging]
  resampleFilter = "box"
  quality = 85
  anchor = "smart"

# Включаем карту сайта и RSS
[sitemap]
  changefreq = "weekly"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
